name: CI - JavaScript

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      cache-key: javascript-build
      run: bazel build //javascript/node/selenium-webdriver:selenium-webdriver

  small-tests:
    name: Small Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Small Tests
      cache-key: javascript-small-tests
      run: bazel test //javascript/node/selenium-webdriver:small-tests

  browser-tests:
    name: Browser Tests
    needs: small-tests
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
          - firefox
    with:
      name: Browser Tests  (${{ matrix.browser }})
      browser: ${{ matrix.browser }}
      cache-key: javascript-${{matrix.browser}}-browser-tests
      run: >
        bazel test
        --flaky_test_attempts 3
        //javascript/node/selenium-webdriver:${{ matrix.browser }}-browser-tests
